{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pizza Sold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "purchase_count_success_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "success"
    },
    {
     "expr": "purchase_count_failure_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Revenue/min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(purchase_revenue_USD_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_utilization_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_utilization_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pizza_creation_latency_milliseconds",
     "legendFormat": "creation latency"
    }
   ]
  },
  {
   "title": "Service Call Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "http_requests_latency_milliseconds",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "http_requests_count_total{endpoint=\"[DELETE] /api/auth\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "http_requests_count_total{endpoint=\"[GET] /\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "http_requests_count_total{endpoint=\"[GET] /api/docs\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "http_requests_count_total{endpoint=\"[GET] /api/franchise\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "http_requests_count_total{endpoint=\"[GET] /api/order/menu\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "http_requests_count_total{endpoint=\"[GET] /api/user/me\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "http_requests_count_total{endpoint=\"[POST] /\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "http_requests_count_total{endpoint=\"[POST] /api/order\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "http_requests_count_total{endpoint=\"[POST] /api/auth\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(source) (http_requests_count_total{source=\"jwt-pizza-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "users_active_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New User Registration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "user_registrations_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    { "expr": "auth_logins_success_total", "legendFormat": "successful logins" },
    {
     "expr": "auth_logins_failure_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "failed logins"
    }
   ]
  }
 ]
}